/// <reference path="../typings/nativescript/1.4/declarations.d.ts" />
/// <reference path="../typings/nativescript/1.4/es6-promise.d.ts" />
/// <reference path="../typings/nativescript/1.4/ui/animation/animation.d.ts" />
/// <reference path="../typings/nativescript/1.4/ui/layouts/layout-base.d.ts" />
/// <reference path="../typings/nativescript/1.4/es-collections.d.ts" />
/// <reference path="../typings/nativescript/1.4/data/observable/observable.d.ts" />
/// <reference path="../typings/nativescript/1.4/data/observable-array/observable-array.d.ts" />
/// <reference path="../typings/nativescript/1.4/ui/core/view.d.ts" />
/// <reference path="../typings/nativescript/1.4/application/application.d.ts" />
/// <reference path="../typings/nativescript/1.4/color/color.d.ts" />
/// <reference path="../typings/nativescript/1.4/ui/core/dependency-observable.d.ts" />
/// <reference path="../typings/nativescript/1.4/ui/core/proxy.d.ts" />
/// <reference path="../typings/nativescript/1.4/ui/core/bindable.d.ts" />
/// <reference path="../typings/nativescript/1.4/ui/content-view/content-view.d.ts" />
/// <reference path="../typings/nativescript/1.4/ui/styling/styling.d.ts" />
/// <reference path="../typings/nativescript/1.4/ui/styling/style-property.d.ts" />
/// <reference path="../typings/nativescript/1.4/ui/styling/css-selector.d.ts" />
/// <reference path="../typings/nativescript/1.4/css/reworkcss.d.ts" />
/// <reference path="../typings/nativescript/1.4/ui/frame/frame.d.ts" />
/// <reference path="../typings/nativescript/1.4/ui/page/page.d.ts" />
/// <reference path="../typings/nativescript/1.4/ui/action-bar/action-bar.d.ts" />
/// <reference path="../typings/nativescript/1.4/ui/layouts/layout.d.ts" />
/// <reference path="../typings/nativescript/1.4/ui/layouts/stack-layout/stack-layout.d.ts" />
/// <reference path="../typings/nativescript/1.4/ui/layouts/dock-layout/dock-layout.d.ts" />
/// <reference path="../typings/nativescript/1.4/ui/gestures/gestures.d.ts" />
/// <reference path="../typings/nativescript/1.4/ui/text-base/text-base.d.ts" />
/// <reference path="../typings/nativescript/1.4/text/formatted-string.d.ts" />
/// <reference path="../typings/nativescript/1.4/text/span.d.ts" />
/// <reference path="../typings/nativescript/1.4/ui/editable-text-base/editable-text-base.d.ts" />
/// <reference path="../typings/nativescript/1.4/ui/text-view/text-view.d.ts" />
/// <reference path="../typings/nativescript/1.4/ui/text-field/text-field.d.ts" />
/// <reference path="../typings/nativescript/1.4/ui/button/button.d.ts" />
/// <reference path="../typings/nativescript/1.4/ui/label/label.d.ts" />
/// <reference path="../typings/nativescript/1.4/ui/switch/switch.d.ts" />

/// DISABLED reference path="../deps/NativeScript/bin/dist/definitions/android17.d.ts" />
/// DISABLED reference path="../deps/NativeScript/bin/dist/definitions/ios.d.ts" />

/// <reference path="../typings/nativescript/android17-dummy.d.ts" />
/// <reference path="../typings/nativescript/ios-dummy.d.ts" />